### ISSUE TITLE
jQuery

### ISSUE THREAD

**Issue by jorgeatgu** [rafagarces/rafa-blot#7]
Bueno, todos hemos usando jQuery y a todos nos ha salvado un montón de tiempo. Pero no merece la pena cargar una librería entera para añadir o quitar clases. Quizás en un proyecto propio no pasa nada, pero trasladar esta práctica a proyectos más grandes es un hack. Sobre todo, si invirtiendo un poco más de tiempo podemos dar con la solución tirando de JavaScript puro y duro.

Esta web esta bien: http://youmightnotneedjquery.com/

Buscar los problemas/soluciones o los métodos que ya usabas de jQuery en stackoverflow acompañado de "vanilla js" también te ayudará.

En este caso he usado classList para quitar y añadir clases: https://developer.mozilla.org/en-US/docs/Web/API/Element/classList

[classList](https://alligator.io/js/classlist/)

```JavaScript
vocales[i].classList.remove(clasesVocales[j]);
vocales[i].classList.add("tipo-b");
```

querySelectorAll para seleccionar todos los selectores

```JavaScript
var vocales = document.querySelectorAll('.logo-web');
```

**Comment by jorgeatgu** [comment]
Tampoco te quiero dar mucho la turra XD

**Comment by rafagarces** [comment]
@jorgeatgu Aprendo aprendo aprendo aprendo aprendo! 
https://media.giphy.com/media/zdBYDzsgpIKYg/giphy.gif
